package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Thursday, 23 March 2017 16:50:45 o'clock CET
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
  void printGameArea (char[][] gameArea, String xTeam, String oTeam);
} // interface ChatCallbackOperations
