package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Thursday, 23 March 2017 16:50:45 o'clock CET
*/

public interface ChatOperations 
{
  boolean join (ChatApp.ChatCallback objref, String name);
  void leave (ChatApp.ChatCallback objref);
  void say (ChatApp.ChatCallback objref, String message);
  void list (ChatApp.ChatCallback objref);
  boolean othelloStart (ChatApp.ChatCallback objref, char color);
  void othelloInsert (ChatApp.ChatCallback objref, int x, int y);
  void othelloLeave (ChatApp.ChatCallback objref);
} // interface ChatOperations
