package ChatApp.ChatCallbackPackage;


/**
* ChatApp/ChatCallbackPackage/GameAreaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Thursday, 23 March 2017 16:50:45 o'clock CET
*/

public final class GameAreaHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[][] = null;

  public GameAreaHolder ()
  {
  }

  public GameAreaHolder (char[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApp.ChatCallbackPackage.GameAreaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApp.ChatCallbackPackage.GameAreaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApp.ChatCallbackPackage.GameAreaHelper.type ();
  }

}
